version: '2'

services:
    events-api:
        build: api
        image: nesterione/events-api
        container_name: events-api
        hostname: events-api
        restart: always

        ports: 
            - "6910:6910"
        environment:
            - DB_URI=<enter your db uri here>
            - DB_NAME=<enter your database name here>

        logging: 
            driver: json-file
         
